### ISSUE TITLE
Can't get it to work on Windows (Cygwin, Babun, Fish shell)

### ISSUE THREAD

**Issue by technopagan** [pmdartus/speedline#18]
Hi!

I'd love to run speedline on my CLI on Windows (not PowerShell). I'm running Cygwin via Babun and Fish Shell, though the problem persists on other Cygwin-based shells on my system, too (MSYS2, Bash, ZSH).

Sadly, the process fails to run under Cygwin/WIN currently. Here's the error message for the default command: 

![capture1](https://cloud.githubusercontent.com/assets/61264/15013475/15344306-1200-11e6-8b48-c4457e96e10e.PNG)

And there's another error when trying to run with the -pretty parameter. I don't know if those 2 errors are related. I've tried both relative & absolute paths to the timeline JSON.

![capture2](https://cloud.githubusercontent.com/assets/61264/15013492/3e1bca82-1200-11e6-87d3-1894f69a5498.PNG)

Am I missing dependencies or is a lib under WIN behaving differently from OSX?

Thank you for your help!

**Comment by pmdartus** [comment]
Hey @technopagan,
For the first error, can you share the timeline file causing this error ? I will try to repro on my machine.
Concerning the second error, the cli accepts this format `speedline <timeline path> [params]`. You just have to put the `--pretty` at the end.

**Comment by pmdartus** [comment]
By the way, what version of node are you using?

**Comment by technopagan** [comment]
Hi again! 

Sorry for taking so long to reply! I've tried SpeedLine again now & got it to work. Since I'm using Chromium Nightly I assume my bug was caused by a quirk in the nightly build back then. Closing this issue now.
