### ISSUE TITLE
Document the Speed Index algorithm

### ISSUE THREAD

**Issue by paulirish** [pmdartus/speedline#2]
are you following the "Visual Progress from Video Capture" approach from https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index ?

**Comment by pmdartus** [comment]
Yes the current implementation uses the **video capture**. I have updated the `README` to make it clearer 6ac7b54a7ca5b5a7c45e8b8345f5ffc201878b04.

I have also open a new issue to implement the **paint event** method #5. Unfortunately the speed index doc is not super clear about how to score each paint event 😕
