### ISSUE TITLE
Set time origin to navigationStart

### ISSUE THREAD

**Issue by paulirish** [pmdartus/speedline#27]
Right now speedline considers time 0 to be the beginning of the trace. However many traces do not start the page load exactly at 0ms. 

Here's the progressive-app.json that we're using as a fixture. navStart here is at 600ms which is a lot later.. :

![image](https://cloud.githubusercontent.com/assets/39191/17795298/fdcb5a64-656b-11e6-8155-88f2a5e7f3f5.png)

Whoops!

Fixing this will change everyone's numbers a bit, but IMO, they'll be much more precise.

I'm proposing we do two things:
1. `speedline('./timeline.json', { timeOrigin: dateObj }).then(...`  -- We add expose an option for the user to pass in a timeOrigin. This would become our new 0, and we'd also crop off any screenshots before this point.
2. navStart detection fallback -- We find the navStart from the trace. Multiple frames and tabs make this harder than you'd think, but I have work for this in Lighthouse that we can use.

Does this make sense? Any alternatives?

**Comment by samccone** [comment]
:+1:

**Comment by pmdartus** [comment]
The first proposal is a really great idea. I am using speedline for measuring page loading in single page applications. This will help reducing the speed index variance introduced by the fact that the recording start doesn't match the click event on the page.

> Multiple frames and tabs make this harder than you'd think
@paulirish In the case where there is a single tab, what is your strategy for detecting the to frame? The `navStart` fallback is also a nice to have! 😄

**Comment by paulirish** [comment]
> @paulirish In the case where there is a single tab, what is your strategy for detecting the to frame? The navStart fallback is also a nice to have! 😄

Basically [something like this](https://github.com/GoogleChrome/lighthouse/blob/b526eb345bd093872308e079b6996cca9291d398/lighthouse-core/lib/traces/tracing-processor.js#L196-L200) .. find first TracingStartedInPage and use its threadID, processID, and frameID to filter to other events on the same thread and in that frame.

And if Chromedriver recorded the trace, there will be no TracingStartedInPage, and we fall back to a suspicious technique of [finding the thread with the most activity](https://github.com/GoogleChrome/lighthouse/blob/b526eb345bd093872308e079b6996cca9291d398/lighthouse-core/config/config.js#L59-L90).  (Probably time to pull this stuff into its own module. I need it all the time.)

**Comment by paulirish** [comment]
Started looking into this and unfortunately it's harder than expected. A trace only has timestamps from the monotonic clock. Measuring difference between these timestamps is very reliable, however they do not at all represent the epoch time. 
And unfortunately there's no representation of the wall time in the trace at all. This means we cannot convert a Date object into any timestamp that is comparable to our trace. :/ 

I'm considering landing a patch to chrome that will add a wall clock timestamp into default traces.
