### ISSUE TITLE
Visual progress calculation from paint events

### ISSUE THREAD

**Issue by pmdartus** [pmdartus/speedline#5]
The current visual progress calculation is based on the **video capture** method.
The [Speed Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index) also provides another approach to calculate the visual progress using the **paint events**.

**Comment by paulirish** [comment]
TBH I think it's unnecessary to use the paint event approach. It's a fallback case because the browser can't look at pixel data. But the metric is intended to be perceptual, so any approach that analyzes color values will be superior to those that dont.

**Comment by paulirish** [comment]
i spoke with the chrome engineer who implemented the paint event algorithm and he indicated it's less accurate. Given that, I think you should close this issue. :)

**Comment by pmdartus** [comment]
Thanks for the update!
