### ISSUE TITLE
Drop bluebird for native Promises?

### ISSUE THREAD

**Issue by samccone** [pmdartus/speedline#7]
You are using bluebird for `.map` but this should be pretty trivial to write with native promises, would you be open to this? 🍝 💀 

--

cc @paulirish

![image](https://cloud.githubusercontent.com/assets/883126/14686750/1302bd36-06ef-11e6-83d2-441b44cf86df.png)

**Comment by pmdartus** [comment]
@samccone sounds goods. I am more than happy to get rid of this dependency. 😄 
 
--

I am using it especially for `Promise.props`. https://github.com/pmdartus/speedline/blob/17d37efa18adffec82917239681a5d995137c77d/src/speed-index.js#L12

**Comment by samccone** [comment]
Great, more than willing to open a PR to do this for you... feel free to assign me to this ticket.

👏

**Comment by paulirish** [comment]
These two are basic polyfills, and do not have any of their own deps:

https://www.npmjs.com/package/promise-props
https://www.npmjs.com/package/promise.map

**Comment by samccone** [comment]
we can just roll our own here, no need for any deps really.
